services:
  discord-bot:
    image: ${DOCKER_REPOSITORY}/${IMAGE_NAME}:latest
    container_name: minecraft-discord-bot
    pull_policy: always
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - DISCORD_MINECRAFT_ADMIN_ROLE=${DISCORD_MINECRAFT_ADMIN_ROLE}
      - CRAFTY_URL=${CRAFTY_URL}
      - CRAFTY_TOKEN=${CRAFTY_TOKEN}
      - CRAFTY_MC_INSTANCE=${CRAFTY_MC_INSTANCE}