services:
  discord-bot:
    image: letf.local:3000/poi/minecraft-discord-bot:latest
    container_name: minecraft-discord-bot
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${{environment.DISCORD_TOKEN}}
      - DISCORD_MINECRAFT_ADMIN_ROLE=${{environment.DISCORD_MINECRAFT_ADMIN_ROLE}}
      - CRAFTY_URL=${{environment.CRAFTY_URL}}
      - CRAFTY_TOKEN=${{environment.CRAFTY_TOKEN}}
      - CRAFTY_MC_INSTANCE=${{environment.CRAFTY_MC_INSTANCE}}