on:
  push:
    branches:
      - main
jobs:
  test:
    uses: ./.forgejo/workflows/test.yaml
    secrets: inherit
  version-bump:
    needs: test
    if: env.FORGEJO_EVENT_NAME == 'push' && env.FORGEJO_HEAD_REF == 'refs/heads/main'
    uses: ./.forgejo/workflows/version.yaml
    secrets: inherit
  build:
    needs: version-bump
    uses: ./.forgejo/workflows/build.yaml
    secrets: inherit
  deploy:
    needs: build
    uses: ./.forgejo/workflows/deploy.yaml
    secrets: inherit