name: Security & Code Analysis
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'LICENSE'
  workflow_call:

jobs:
  scan:
    runs-on: docker
    container:
      image: quay.io/podman/stable
    steps:
      - run: |
          echo "prepare scan environment"
          dnf install -y node git

      - uses: https://data.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug URL Variables
        run: |
          echo "Sonar URL is '${{ vars.SONAR_URL }}'"
          echo "Sonar URL is '${{ vars.DTRACK_API_URL }}'"

      - name: SonarQube Scan
        uses: https://github.com/sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_URL }}

      - name: Generate SBOM via Trivy CLI
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
          trivy fs --format cyclonedx --output sbom.json .

      - name: Upload SBOM to Dependency-Track
        env:
          DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
          DTRACK_API_URL: ${{ vars.DTRACK_API_URL }}
        run: |
          CALL_URL=$DTRACK_API_URL/api/v1/bom
          echo "The call URL for culr is: $CALL_URL"
          curl -X "POST" "$CALL_URL" \
               -H 'Content-Type: multipart/form-data' \
               -H "X-Api-Key: $DTRACK_API_KEY" \
               -F "autoCreate=true" \
               -F "projectName=${GITHUB_REPOSITORY#*/}" \
               -F "projectVersion=${{ github.ref_name }}" \
               -F "bom=@sbom.json"