name: Security & Code Analysis
on: [workflow_call, pull_request]

jobs:
  scan:
    runs-on: docker
    container:
      image: quay.io/podman/stable
    steps:
      - run: |
          echo "prepare build environment"
          dnf install -y node git skopeo

      - uses: https://data.forgejo.org/actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug URL Variables
        run: |
          echo "Sonar URL is '${{ vars.SONAR_URL }}'"
          echo "Sonar URL is '${{ vars.DTRACK_API_URL }}'"

      - name: SonarQube Scan
        uses: https://github.com/sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ vars.SONAR_URL }}

      - name: Generate SBOM
        env: 
          CONTAINERS_STORAGE_DRIVER: vfs
        run: |
          podman run --rm -v .:/src -w /src ghcr.io/aquasecurity/trivy:latest fs --format cyclonedx --output sbom.json .

      - name: Gets project name from repo
        run: |
          PROJECT_NAME=$(echo "${{ env.FORGEJO_REPOSITORY }}" | tr '[:upper:]' '[:lower:]')
      - name: Upload SBOM to Dependency-Track
        env:
          DTRACK_API_KEY: ${{ secrets.DTRACK_API_KEY }}
          DTRACK_API_URL: ${{ vars.DTRACK_API_URL }}
        run: |
          curl -X "POST" "$DTRACK_API_URL/api/v1/bom" \
               -H 'Content-Type: multipart/form-data' \
               -H "X-Api-Key: $DTRACK_API_KEY" \
               -F "autoCreate=true" \
               -F "projectName=$PROJECT_NAME" \
               -F "projectVersion=${{ github.ref_name }}" \
               -F "bom=@sbom.json"