name: tests
on:
  pull_request:
    branches:
      - main
  workflow_call:
jobs:
  test:
    runs-on: docker
    container:
      image: node:lts-alpine
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4
      - name: Install dependencies
        run: npm i --include=dev --loglevel silent
      - name: Run tests
        run: npm test