kind: pipeline
name: build

steps:
  - name: build-and-push
    image: plugins/docker
    settings:
      registry: letf.local:3000
      repo: letf.local:3000/poi/minecraft-discord-bot
      tags:
        - latest
        - ${CI_COMMIT_TAG}
      username:
        from_secret: registry_user
      password:
        from_secret: registry_password
      insecure: true
      daemon_off: false
      network_mode: host
when:
  - event: [tag]
  - event: [manual]
  - event: [push]
    branch: [main]