# kind: pipeline
# name: build-and-push

steps:
  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      registry: letf.local:3000
      repo: letf.local:3000/poi/minecraft-discord-bot
      tags:
        - latest
        - ${CI_COMMIT_TAG}
      username:
        from_secret: registry_username
      password:
        from_secret: registry_password
      insecure: true
      buildkit_config: |
        [registry."letf.local:3000"]
          http = true
          insecure = true
  - name: calculate-version
    image: ghcr.io/caarlos0/svu
    commands:
      - export NEXT_VERSION=$(svu next)
      - echo "Next version is $NEXT_VERSION"
when:
  - event: [tag]
  - event: [push]
    branch: [main]